[package]
name = "img"
version = "0.1.0"
edition = "2024"

[dependencies]
png = "0.17.16"
rayon = { version = "1.10.0", optional = true }
thiserror = "2.0.12"

[features]
default = ["parallel"]
parallel = ["dep:rayon"]
