name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Build with parallel flag
      run: cargo build --featurese parallel --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run tests with parallel flag
      run: cargo test --featurese parallel --verbose
